name: Release
on:
  pull_request:
    branches:
      - master
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  BIN_NAME: drm-vc4-grabber
  PROJECT_NAME: drm-vc4-grabber
  REPO_NAME: rudihorn/drm-vc4-grabber

jobs:
  dist:
    name: Dist
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build: [aarch64-linux]
        include:
        - build: aarch64-linux
          os: ubuntu-20.04
          rust: stable
          target: aarch64-unknown-linux-musl

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install ${{ matrix.rust }} toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true

      - name: Install cross
        run: cargo install cross

      - name: Build release binary
        env:
          TARGET: ${{ matrix.target }}
          PLATFORM: ${{ matrix.build }}
        run: ./scripts/build.sh

      - uses: actions/upload-artifact@v4
        with:
          name: bins-${{ matrix.build }}
          path: bins-${{ matrix.build }}

  publish:
    name: Publish
    needs: [dist]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          submodules: false

      - uses: actions/download-artifact@v4

      - name: Calculate tag name
        run: |
          name=dev
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            name=${GITHUB_REF:10}
          fi
          echo TAG=$name >> $GITHUB_ENV
        id: tagname

      - name: Build archive
        run: ./scripts/package.sh

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          file_glob: true
          tag: ${{ env.TAG }}
          overwrite: true
